# Generated by Django 3.0.7 on 2020-06-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('uri', models.CharField(max_length=70)),
                ('href', models.URLField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('duration_ms', models.PositiveIntegerField()),
                ('explicit', models.BooleanField()),
                ('disc_number', models.PositiveSmallIntegerField()),
                ('href', models.URLField(max_length=500, null=True)),
                ('is_local', models.BooleanField()),
                ('is_playable', models.BooleanField()),
                ('preview_url', models.CharField(max_length=500)),
                ('truck_number', models.PositiveSmallIntegerField()),
                ('uri', models.CharField(max_length=70)),
                ('artists', models.ManyToManyField(to='songs.Artist')),
            ],
        ),
    ]
