# Generated by Django 3.0.7 on 2020-06-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='type_field',
            field=models.CharField(default='artist', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artist',
            name='external_urls',
            field=models.ManyToManyField(to='songs.Url'),
        ),
    ]
