# Generated by Django 3.0.7 on 2020-06-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20200629_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='type',
            field=models.CharField(default='truck', max_length=20),
        ),
    ]
