# Generated by Django 3.0.7 on 2020-06-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_song_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='external_urls',
            field=models.ManyToManyField(to='songs.Url'),
        ),
    ]
