# Generated by Django 3.0.7 on 2020-06-30 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_auto_20200629_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='external_urls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.Url'),
        ),
        migrations.AlterField(
            model_name='song',
            name='external_urls',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.Url'),
        ),
        migrations.AlterField(
            model_name='song',
            name='is_local',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='is_playable',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='preview_url',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='truck_number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
