# Generated by Django 3.0.7 on 2020-06-30 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_auto_20200630_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='external_urls',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='songs.Url'),
        ),
    ]
