# Generated by Django 3.0.7 on 2020-06-30 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_auto_20200630_1047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='truck_number',
            new_name='track_number',
        ),
    ]
