# Generated by Django 3.0.7 on 2020-06-30 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0009_auto_20200630_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='type_field',
            new_name='type',
        ),
    ]
